/hik_camera:
  ros__parameters:
    camera_name: narrow_stereo

    exposure_time: 6000
    gain: 32.0
    acquisition_frame_rate: 10.0
    image_width: 640
    image_height: 480
    offset_x: 0
    offset_y: 0
    publish_rate: 0.0



